- app.js
- bin/countrie.js
- router/auth.js
- views/auth/signin.hbs
- views/auth/signup.hbs
> Signin routes and session

- views/auth/signin.hbs
- views/auth/signup.hbs
> close x forms fixed

- app.js
- models/record.js
- router/auth.js
- router/private.js
- views/partials/addCommentPartial.hbs
- views/private/add-comment.hbs
- views/private/wall.hbs
> comment added to wall

- app.js
- public/stylesheets/style.scss
> Fix @import profile

- .gitignore
- router/private.js
- views/private/deleteaccount.hbs
- views/private/deleted.hbs
- views/private/edituser.hbs
> ![gif](https://media.giphy.com/media/7ILa7CZLxE0Ew/giphy.gif)

- app.js
- models/record.js
- router/private.js
- views/private/add-comment.hbs
> done private message option + favicon

- package.json
- public/stylesheets/auth.scss
- public/stylesheets/style.scss
- views/auth/signin.hbs
- views/auth/signup.hbs
- views/layout.hbs
> Finished CSS signin form

- public/stylesheets/auth.scss
- views/auth/signup.hbs
> Finished signup css

- public/stylesheets/navbar.scss
- public/stylesheets/profile.scss
- public/stylesheets/style.scss
- router/private.js
- views/auth/signup.hbs
- views/partials/navbarPartial.hbs
- views/private/profile.hbs
> Finished navbar

- public/stylesheets/profile.scss
- public/stylesheets/style.scss
- public/stylesheets/wall.scss
- views/private/profile.hbs
- views/private/wall.hbs
> Finished CSS profile

- public/stylesheets/delete-account.scss
- public/stylesheets/style.scss
- views/private/deleteaccount.hbs
> Finished CSS delete account

- public/stylesheets/deleted.scss
- public/stylesheets/style.scss
- views/private/deleted.hbs
> Finished CSS confirmation deleted account

- public/stylesheets/wall.scss
> Finished CSS Wall

- public/stylesheets/add-comment.scss
- public/stylesheets/checkbox.scss
- public/stylesheets/style.scss
- views/private/add-comment.hbs
> Finished CSS rate and comment

- public/stylesheets/wall.scss
- views/private/wall.hbs
> Fixed thums-up icon

- public/stylesheets/profile.scss
> Fixed margin photo profile

- router/index.js
- views/layout.hbs
> auto-login and fix flash-messages

- public/stylesheets/navbar.scss
- router/chat.js
- router/private.js
- views/chat/chat.hbs
- views/partials/navbarPartial.hbs
> Finished chat in navbar

- bin/www
- public/stylesheets/chat.scss
- router/chat.js
- views/chat/chat.hbs
> Finished CSS Chat - Split messages chat

- public/stylesheets/chat.scss
- router/chat.js
- views/chat/chat.hbs
> Finished CSS Chat - Split messages chat - fadein - fadeout

- public/stylesheets/chat.scss
> Finished CSS Chat - Split messages chat - fadein - fadeout-margins

- bin/www
- router/chat.js
- views/chat/chat.hbs
> Chat notifications
